server:
  port: 8080
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 5
service-provider: # \u670D\u52A1\u5668\u540D\uFF0C\u8D1F\u8F7D\u5747\u8861\u968F\u673A
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # \u8BBE\u7F6Ehystrix\u7684\u8D85\u65F6\u65F6\u95F4\u4E3A6000ms
circuitBreaker:
  requestVolumeThreshold: 10 # \u89E6\u53D1\u7194\u65AD\u7684\u6700\u5C0F\u8BF7\u6C42\u6B21\u6570\uFF0C\u9ED8\u8BA420
  circuitBreaker.sleepWindowInMilliseconds: 10000 # \u4F11\u7720\u65F6\u957F\uFF0C\u9ED8\u8BA4\u662F5000\u6BEB\u79D2
  circuitBreaker.errorThresholdPercentage: 50 # \u89E6\u53D1\u7194\u65AD\u7684\u5931\u8D25\u8BF7\u6C42\u6700\u5C0F\u5360\u6BD4\uFF0C\u9ED8\u8BA450%
feign:
  hystrix:
    enabled: true # \u5F00\u542FFeign\u7684\u7194\u65AD\u529F\u80FD \uFF0C\u9ED8\u8BA4false