server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///leyou
    username: root
    password: 123456
  application:
    name: service-provider # \u5E94\u7528\u540D\u79F0\uFF0C\u6CE8\u518C\u5230eureka\u540E\u7684\u670D\u52A1\u540D\u79F0
mybatis:
  type-aliases-package: cn.lunyh.service.pojo
eureka:
  client:
    service-url: # EurekaServer\u5730\u5740
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true # \u670D\u52A1\u63D0\u4F9B\u65B9\u542F\u52A8\u65F6\uFF0C\u4F1A\u68C0\u6D4B\u8BE5\u53C2\u6570\u662F\u5426\u4E3Atrue\uFF0Ctrue-\u6CE8\u518C\u7ED9eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # \u5FC3\u8DF3\u65F6\u95F4
    lease-expiration-duration-in-seconds: 15 # \u8FC7\u671F\u65F6\u95F4